### ISSUE TITLE
Add English language 

### ISSUE THREAD

**Issue by xmha97** [thxbrop/M3UAndroid#5]
Add English language:

![Screenshot_2023-03-09-00-40-44-017_com m3u app](https://user-images.githubusercontent.com/23485114/223850887-a5f22366-0dcc-4d97-82ce-ea77b704ec8e.jpg)

**Comment by thxbrop** [comment]
OK, waiting to next version please 👀

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by thxbrop** [comment]
> Thanks 🙏

https://github.com/thxbrop/M3UAndroid/releases/tag/v1.11.0-alpha02

**Comment by thxbrop** [comment]
Please try latest package (1.11.0-alpha03), alpha02 supports English language and alpha03 fix an importance bug.

**Comment by xmha97** [comment]
Thanks 🙏
